// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class MissingarticlenumberandsizetableTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void missingarticlenumberandsizetable() {
    driver.Navigate().GoToUrl("https://www.exza.bg/");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 840);
    driver.FindElement(By.XPath("(//a[contains(text(),\'Рокли\')])[2]")).Click();
    driver.FindElement(By.XPath("//a[@id=\'yui_3_12_0_1_1680382591335_873\']")).Click();
    {
      var elements = driver.FindElements(By.XPath("//div[2]/div/p/img"));
      Assert.True(elements.Count == 0);
    }
    {
      var elements = driver.FindElements(By.XPath("//span[contains(.,\'Арт. №:\')]"));
      Assert.True(elements.Count == 0);
    }
    driver.Close();
  }
}
