// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class MissinginbformationforreturndeadlineandfastshippingTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void missinginbformationforreturndeadlineandfastshipping() {
    driver.Navigate().GoToUrl("https://www.exza.bg/");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 840);
    driver.FindElement(By.XPath("(//a[contains(text(),\'Връхни дрехи\')])[2]")).Click();
    driver.FindElement(By.XPath("//img[@alt=\'Парка с огромен  пух \']")).Click();
    {
      var elements = driver.FindElements(By.CssSelector(".right"));
      Assert.True(elements.Count == 0);
    }
    driver.Close();
  }
}
