// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class ProductsortbuttonnotworkingproperlyTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void productsortbuttonnotworkingproperly() {
    driver.Navigate().GoToUrl("https://www.exza.bg/");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 840);
    driver.FindElement(By.XPath("(//a[contains(text(),\'Поли\')])[2]")).Click();
    var elements = driver.FindElements(By.XPath("//a[contains(text(),\'Модерен дамски пола/панталон в розово PO57\')]"));
    Assert.True(elements.Count > 0);
    driver.FindElement(By.XPath("//button[@id=\'yui_3_12_0_1_1680384261467_678\']")).Click();
    driver.FindElement(By.XPath("//div[@id=\'yui_3_12_0_1_1680384261467_605\']/ol/li[6]")).Click();
    var elements = driver.FindElements(By.XPath("//a[contains(text(),\'Модерен дамски пола/панталон в розово PO57\')]"));
    Assert.True(elements.Count > 0);
    driver.Close();
  }
}
