// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TwowronginformationforreturndeadlineTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void twowronginformationforreturndeadline() {
    driver.Navigate().GoToUrl("https://www.exza.bg/");
    driver.Manage().Window.Size = new System.Drawing.Size(1058, 814);
    Assert.That(driver.FindElement(By.XPath("//a[contains(text(),\'14 дни право на връщане\')]")).Text, Is.EqualTo("14 ДНИ ПРАВО НА ВРЪЩАНЕ"));
    driver.FindElement(By.XPath("//a[contains(text(),\'14 дни право на връщане\')]")).Click();
    Assert.That(driver.FindElement(By.CssSelector("ul:nth-child(17) > li:nth-child(1)")).Text, Is.EqualTo("Според разпоредбите на чл. 55 от ЗЗП, потребителят има право да върне закупената от него стока в рамките на 14 работни дни от датата на закупуването й. За целта предметът на сделката трябва да бъде в оригинална опаковка, без следи от употреба или нарушаване на търговския вид на стоката."));
    driver.FindElement(By.XPath("//img[@alt=\'ExXxtravaganza\']")).Click();
    driver.FindElement(By.CssSelector("#yui_3_12_0_1_1680379749185_357 > img")).Click();
    var elements = driver.FindElements(By.XPath("//p[3]/img"));
    Assert.True(elements.Count > 0);
    driver.Close();
  }
}
