// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class LovedButtonRedirectToLoginAndRegistarFormTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void lovedButtonRedirectToLoginAndRegistarForm() {
    driver.Navigate().GoToUrl("https://www.bogdanmebel.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 840);
    var elements = driver.FindElements(By.CssSelector(".top-menu-item-5 > a"));
    Assert.True(elements.Count > 0);
    driver.FindElement(By.CssSelector(".top-menu-item-5 > a")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".col-sm-6:nth-child(1) .title")).Text, Is.EqualTo("НОВ КЛИЕНТ"));
    Assert.That(driver.FindElement(By.CssSelector(".col-sm-6:nth-child(2) .title")).Text, Is.EqualTo("РЕГИСТРИРАН КЛИЕНТ"));
    driver.Close();
  }
}
