// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class RegistrationwithinvaliddataTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void registrationwithinvaliddata() {
    driver.Navigate().GoToUrl("https://www.oree.co.uk/");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 840);
    var elements = driver.FindElements(By.CssSelector(".icon-user > path:nth-child(1)"));
    Assert.True(elements.Count > 0);
    driver.FindElement(By.CssSelector(".icon-user")).Click();
    Assert.That(driver.FindElement(By.XPath("//a[contains(text(),\'Create account\')]")).Text, Is.EqualTo("Create account"));
    driver.FindElement(By.XPath("//a[contains(text(),\'Create account\')]")).Click();
    driver.FindElement(By.Id("FirstName")).SendKeys("!@#$");
    driver.FindElement(By.Id("LastName")).SendKeys("!@#$");
    driver.FindElement(By.Id("Email")).SendKeys("tes@tesing.te");
    driver.FindElement(By.Id("CreatePassword")).SendKeys("123456");
    var elements = driver.FindElements(By.CssSelector(".account-form__submit"));
    Assert.True(elements.Count > 0);
    driver.FindElement(By.CssSelector(".account-form__submit")).Click();
    driver.FindElement(By.XPath("//svg[contains(@aria-hidden,\'true\')]")).Click();
    Assert.That(driver.FindElement(By.XPath("//h3[@class=\'size--heading-2\'][contains(.,\'Account Details\')]")).Text, Is.EqualTo("Account Details"));
    driver.FindElement(By.LinkText("Sign Out")).Click();
    driver.Close();
  }
}
