// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class ShoppingCartButtonDisappearAndOnlySeeNumberOfOrdersTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void shoppingCartButtonDisappearAndOnlySeeNumberOfOrders() {
    driver.Navigate().GoToUrl("https://www.oree.co.uk/");
    driver.Manage().Window.Size = new System.Drawing.Size(1538, 926);
    driver.FindElement(By.CssSelector(".icon-croissant")).Click();
    var elements = driver.FindElements(By.CssSelector(".icon-croissant"));
    Assert.True(elements.Count > 0);
    driver.FindElement(By.XPath("(//a[contains(text(),\'Order Online\')])[3]")).Click();
    {
      var elements = driver.FindElements(By.CssSelector(".icon-croissant"));
      Assert.True(elements.Count == 0);
    }
    driver.FindElement(By.CssSelector("#CollectionBlock--list-collections-page-template-1 .collection-block__info")).Click();
    driver.FindElement(By.XPath("//a[contains(text(),\'Lemon Yuzu Tart\')]")).Click();
    driver.FindElement(By.Name("add")).Click();
    driver.FindElement(By.CssSelector(".logo__image--default")).Click();
    driver.FindElement(By.XPath("(//a[contains(text(),\'Order Online\')])[3]")).Click();
    var elements = driver.FindElements(By.CssSelector(".icon-croissant"));
    Assert.True(elements.Count > 0);
    driver.Close();
  }
}
