// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class CheckautorizationbuttonforageTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void checkautorizationbuttonforage() {
    driver.Navigate().GoToUrl("https://chochko.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1054, 808);
    driver.FindElement(By.CssSelector("#ui-id-2 > span:nth-child(2)")).Click();
    {
      var element = driver.FindElement(By.CssSelector("#ui-id-2 > span:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    js.ExecuteScript("window.scrollTo(0,605.5999755859375)");
    js.ExecuteScript("window.scrollTo(0,1115.199951171875)");
    Assert.That(driver.FindElement(By.CssSelector(".sub-category:nth-child(8) > .category-item-title")).Text, Is.EqualTo("Торти 18+"));
    driver.FindElement(By.CssSelector(".sub-category:nth-child(8) > .category-item-title")).Click();
    var elements = driver.FindElements(By.CssSelector(".modal-footer"));
    Assert.True(elements.Count > 0);
    driver.FindElement(By.CssSelector(".modal-footer")).Click();
  }
}
