// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class RegistrationwithinvaliddataTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void registrationwithinvaliddata() {
    driver.Navigate().GoToUrl("https://www.parts.bg/");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 840);
    Assert.That(driver.FindElement(By.LinkText("Регистрация")).Text, Is.EqualTo("Регистрация"));
    driver.FindElement(By.LinkText("Регистрация")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(2) .text")).SendKeys("tete@tete.tete");
    driver.FindElement(By.CssSelector("tr:nth-child(3) > td:nth-child(3)")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(3) .text")).SendKeys("1234567");
    driver.FindElement(By.Name("confirm_password")).SendKeys("1234567");
    driver.FindElement(By.Name("first_name")).SendKeys("!@#");
    driver.FindElement(By.Name("last_name")).SendKeys("!@#");
    driver.FindElement(By.Name("mobile")).SendKeys("0888888888888888");
    driver.FindElement(By.Name("city")).Click();
    {
      var dropdown = driver.FindElement(By.Name("city"));
      dropdown.FindElement(By.XPath("//option[. = 'София']")).Click();
    }
    driver.FindElement(By.Id("accept_terms")).Click();
    var elements = driver.FindElements(By.CssSelector(".submitButton > input"));
    Assert.True(elements.Count > 0);
    driver.FindElement(By.CssSelector(".submitButton > input")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".rmtk_msg td:nth-child(2)")).Text, Is.EqualTo("Регистрацията Ви беше успешна."));
    driver.FindElement(By.CssSelector(".sfHover > .sf-with-ul")).Click();
    driver.FindElement(By.LinkText("Лични данни")).Click();
    Assert.That(driver.FindElement(By.LinkText("изход")).Text, Is.EqualTo("изход"));
    driver.FindElement(By.LinkText("изход")).Click();
    driver.Close();
  }
}
