// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class ThePictureDoesntLoadInTheShippingInstructionTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void thePictureDoesntLoadInTheShippingInstruction() {
    driver.Navigate().GoToUrl("https://www.bogdanmebel.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 840);
    Assert.That(driver.FindElement(By.CssSelector(".links-menu-72 .links-menu-item-2 .links-text")).Text, Is.EqualTo("Доставка и плащане"));
    driver.FindElement(By.CssSelector(".links-menu-72 .links-menu-item-2 .links-text")).Click();
    {
      WebDriverWait wait = new WebDriverWait(driver, System.TimeSpan.FromSeconds(30));
      wait.Until(driver => driver.FindElements(By.XPath("//img[contains(@src,\'https://memo.bg/images/e-pay2-memo.jpg\')]")).Count > 0);
    }
    driver.Close();
  }
}
