// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TimeForPromotionIsOverOffertStillExistTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void timeForPromotionIsOverOffertStillExist() {
    driver.Navigate().GoToUrl("https://www.bogdanmebel.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 840);
    Assert.That(driver.FindElement(By.CssSelector(".multi-level:nth-child(2) .links-text")).Text, Is.EqualTo("ПРОМОЦИИ"));
    driver.FindElement(By.CssSelector(".multi-level:nth-child(2) .links-text")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".product-layout:nth-child(2) .name > a")).Text, Is.EqualTo("ШКАФ ЗА ОБУВКИ BM-LIMA ST-2 1"));
    driver.FindElement(By.CssSelector(".product-layout:nth-child(2) .name > a")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".countdown > div:nth-child(2)")).Text, Is.EqualTo("00\\\\nЧаса"));
    Assert.That(driver.FindElement(By.CssSelector(".countdown > div:nth-child(3)")).Text, Is.EqualTo("00\\\\nМин"));
    driver.Close();
  }
}
